### ISSUE TITLE
TODO. 검색엔진 최적화(SEO) 플러그인 적용 또는 제작

### ISSUE THREAD

**Issue by limdongjin** [limdongjin/TIL#1]
# TODO

포스트(md파일)의 제목,내용 요약,url을 자동으로 메타태그에 추가해주도록 한다. 

## 왜 필요한가? 

vuepress는 현재 SEO를 완전히 지원해주지않으며 포스트의 제목과 내용, url 등의 메타 정보를 seo를 위한 메타태그들에 자동으로 넣어주지않는다. 그래서 글을 쓸때마다 SEO 최적화를 위한 meta 태그들( title, description, og:*  등)에 일일이 제목, 내용, url을 작성해주어야하는 번거로움이 생긴다. 

```
# Current SEO Example
---
title: 알고리즘 평가방법. 시간 복잡도
meta: 
  - name: description
    content: 알고리즘의 평가방법중 하나인 시간복잡도에 대헤 알아봅니다.
  - property: og:title
    content: 알고리즘 평가방법. 시간복잡도
  - property: og:description
    content:  알고리즘의 평가방법중 하나인 시간복잡도에 대헤 알아봅니다.
  - property: og:url
    content: https://limdongjin.github.io/algorithms/analysis
---
# 알고리즘 평가방법. 시간 복잡도

~~
```

## 어떻게 해결할것인가?

1. 우선 vuepress의 beta 릴리즈에서 SEO를 어떻게 지원해주는지보고 자체구현할것인지 결정한다.
